"""Initial schema with vehicles, campaigns, contacts, admin_users

Revision ID: 9c886cc84ac2
Revises: 
Create Date: 2026-01-14 16:41:55.239710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c886cc84ac2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('supabase_user_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('supabase_user_id')
    )
    op.create_index(op.f('ix_admin_users_email'), 'admin_users', ['email'], unique=True)
    op.create_table('campaigns',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('discount_percentage', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('applicable_vehicle_ids', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_is_active'), 'campaigns', ['is_active'], unique=False)
    op.create_table('contacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacts_email'), 'contacts', ['email'], unique=False)
    op.create_index(op.f('ix_contacts_read'), 'contacts', ['read'], unique=False)
    op.create_table('vehicles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('fuel_type', sa.String(length=50), nullable=False),
    sa.Column('mileage', sa.Integer(), nullable=False),
    sa.Column('transmission', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=False),
    sa.Column('power', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('features', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('images', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('is_sold', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_brand'), 'vehicles', ['brand'], unique=False)
    op.create_index(op.f('ix_vehicles_fuel_type'), 'vehicles', ['fuel_type'], unique=False)
    op.create_index(op.f('ix_vehicles_is_featured'), 'vehicles', ['is_featured'], unique=False)
    op.create_index(op.f('ix_vehicles_is_sold'), 'vehicles', ['is_sold'], unique=False)
    op.create_index(op.f('ix_vehicles_price'), 'vehicles', ['price'], unique=False)
    op.create_index(op.f('ix_vehicles_year'), 'vehicles', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicles_year'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_price'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_is_sold'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_is_featured'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_fuel_type'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_brand'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_contacts_read'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_email'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_campaigns_is_active'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_admin_users_email'), table_name='admin_users')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
